security:
    enable_authenticator_manager: true
    encoders:
        App\Entity\User:
            algorithm: auto
    
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_auth:
            pattern: ^/api/app_login
            lazy: true
            provider: app_user_provider
            json_login:
                check_path: /api/app_login
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        api:
            pattern: ^/api/app/
            stateless: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppAuthenticator
            guard:
                authenticators:
                    - App\Security\AppAuthenticator
            entry_point: App\Security\AppAuthenticator
            logout:
                path: app_logout
    
    access_control:
        - { path: ^/api/ag/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/web/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user/, roles: [ROLE_USER] }
        - { path: ^/api/admin/, roles: [ROLE_ADMIN,ROLE_DEVELOPER] }
