stages:
  - build
  - deploy

build:
   tags:
      - atmadev
   stage: build
   script:
      - yarn install
      - yarn build
   cache:
      key: build-cache
      paths:
         - vendor/
         - public/bundles/
         - public/js/

Deploy to dev:
  stage: deploy
  environment:
    name: dev
    url: https://pbr.atmadev.ru/
  when: manual
  tags:
    - atmadev
  only:
    - master
  script:
    - curl -sS https://getcomposer.org/installer | /usr/local/php-8/bin/php
    - mv env .env
    - /usr/local/php-8/bin/php composer.phar install
    - rsync --exclude '.git' --exclude 'var/cache' --exclude '.env' --exclude '.gitlab-ci.yml' -avzh . /www/pbr.atmadev.ru
    - cd /www/pbr.atmadev.ru
    - /usr/local/php-8/bin/php bin/console doctrine:migrations:migrate --env=dev --no-interaction
    - /usr/local/php-8/bin/php bin/console cache:clear
  cache:
    key: build-cache
    paths:
      - vendor/
      - public/bundles/
      - public/js/
