authentication_token:
  path: /api/app_login
  methods: ['POST']

auto_redirect:
  path: /redirect
  controller: App\Controller\MainController::auto_redirect
api_upload:
  path: /api/upload/
  controller: App\Controller\MainController::upload
api_close_issue:
  path: /api/closeIssue
  controller: App\Controller\IdeasController::closeIssue

api_user_new:
  path: /api/user/new/
  controller: App\Controller\UserController::newUser
api_user_register:
  path: /api/user/register/
  controller: App\Controller\UserController::register
api_profile:
  path: /api/profile/
  controller: App\Controller\UserController::getProfile
api_user_setProfile:
  path: /api/user/setProfile/
  controller: App\Controller\UserController::setProfile
api_user_set_username:
  path: /api/user/setUsername/
  controller: App\Controller\UserController::setUsername
api_user_profile:
  path: /api/users/{id}/
  controller: App\Controller\UserController::getUserProfile

api_ideas_search:
  path: /ideas/api/search/
  controller: App\Controller\IdeasController::search
api_get_categories:
  path: /ideas/api/getCategories/
  controller: App\Controller\IdeasController::getCategories
api_get_ideas:
  path: /ideas/api/getIdeas/{category_id}/
  controller: App\Controller\IdeasController::getIdeas
  requirements:
    id: \d+
api_add_idea:
  path: /ideas/api/add_idea/
  controller: App\Controller\IdeasController::add_idea
api_new_idea:
  path: /ideas/api/new/
  controller: App\Controller\IdeasController::new_idea
api_set_status:
  path: /ideas/api/setStatus/
  controller: App\Controller\IdeasController::setStatus
api_new_vote:
  path: /ideas/api/newVote/
  controller: App\Controller\IdeasController::newVote
api_unvote:
  path: /api/delete/vote/
  controller: App\Controller\IdeasController::unVote
api_delete_comment:
  path: /api/delete/comment/
  controller: App\Controller\IdeasController::deleteComment
api_new_comment:
  path: /ideas/api/newComment/
  controller: App\Controller\IdeasController::newComment

idea_show:
  path: /idea/


app_signup:
  path: /signup
  controller: App\Controller\SecurityController::signup
app_login:
  path: /login
  methods: ['POST']
  controller: App\Controller\SecurityController::login


login_app:
  path: /login-app/{param}/
  controller: App\Controller\AssociationController::loginApp
default:
  path:  /{wildcard}
  controller: App\Controller\MainController::index
  requirements:
    wildcard: .*

homepage:
  path: /{_locale}/{wildcard}/
  controller: App\Controller\MainController::index
  requirements:
    _locale: en|ru
    wildcard: .*

#api_user_get:
#  path: /api/users/{id}/
#  controller: App\Controller\UserController::getUserProfile
#  requirements:
#    id: \d+