authentication_token:
  path: /api/app_login
  methods: ['POST']

api_addTipData:
  path: /api/addTipData/
  controller: App\Controller\IdeasController::importPhpBackData

# Роуты для atmaguru
api_close_issue:
  path: /api/ag/closeIssue
  controller: App\Controller\IdeasController::closeIssue
api_add_idea:
  path: /api/ag/ideas/add_idea/
  controller: App\Controller\IdeasController::add_idea
api_user_register:
  path: /api/ag/register/
  controller: App\Controller\UserController::register
api_user_get_by_email:
  path: /api/ag/getUserByEmail/
  controller: App\Controller\UserController::getUserByEmail
api_user_set_username:
  path: /api/ag/user/setUsername/
  controller: App\Controller\UserController::setUsername

# Роуты общедоступные
api_decode_user:
  path: /api/web/decode/user/
  controller: App\Controller\MainController::decodeUserInfo
api_upload:
  path: /api/web/upload/
  controller: App\Controller\MainController::upload
api_redirect:
  path: /api/web/redirect/
  controller: App\Controller\UserController::redirectToReact
api_signIn:
  path: /api/web/signIn/
  controller: App\Controller\UserController::signIn
api_profile:
  path: /api/web/profile/
  controller: App\Controller\UserController::getProfile
api_user_profile:
  path: /api/web/user/{id}/
  controller: App\Controller\UserController::getUserProfile
api_ideas_search:
  path: /api/web/ideas/search/
  controller: App\Controller\IdeasController::search
api_get_categories:
  path: /api/web/ideas/getCategories/
  controller: App\Controller\IdeasController::getCategories
api_get_ideas:
  path: /api/web/ideas/getIdeas/
  controller: App\Controller\IdeasController::getIdeas
api_get_idea:
  path: /api/web/idea/{idea_id}/
  controller: App\Controller\IdeasController::getIdea
api_delete_idea:
  path: /api/web/delete/idea/
  controller: App\Controller\IdeasController::deleteIdea

# Роуты пользователей
api_new_idea:
  path: /api/user/ideas/new/
  controller: App\Controller\IdeasController::new_idea
api_new_vote:
  path: /api/user/ideas/newVote/
  controller: App\Controller\IdeasController::newVote
api_unvote:
  path: /api/user/delete/vote/
  controller: App\Controller\IdeasController::unVote
api_new_comment:
  path: /api/user/ideas/newComment/
  controller: App\Controller\IdeasController::newComment
api_check_all_comments:
  path: /api/user/ideas/checkAllComments/
  controller: App\Controller\IdeasController::checkAllComments
api_change_comment:
  path: /api/user/ideas/changeComment/
  controller: App\Controller\IdeasController::changeComment
api_user_setProfile:
  path: /api/user/setProfile/
  controller: App\Controller\UserController::setProfile

# Как для админа так и для пользователя
api_delete_comment:
  path: /api/user/delete/comment/
  controller: App\Controller\IdeasController::deleteComment
api_change_idea:
  path: /api/user/idea/changeIdea/
  controller: App\Controller\IdeasController::changeIdea

# Роуты админа
api_set_official_comment:
  path: /api/admin/ideas/setOfficialComment/
  controller: App\Controller\IdeasController::setOfficialComment
api_set_category:
  path: /api/admin/ideas/setCategory/
  controller: App\Controller\IdeasController::setCategory
api_set_type:
  path: /api/admin/ideas/setType/
  controller: App\Controller\IdeasController::setType
api_set_status:
  path: /api/admin/ideas/setStatus/
  controller: App\Controller\IdeasController::setStatus
api_set_role:
  path: /api/admin/ideas/setRole/
  controller: App\Controller\UserController::setRole


# роуты реакта
auto_redirect:
  path: /redirect
idea_show:
  path: /idea/


app_signup:
  path: /signup
  controller: App\Controller\SecurityController::signup
app_login:
  path: /login
  methods: ['POST']
  controller: App\Controller\SecurityController::login


login_app:
  path: /login-app/{param}/
  controller: App\Controller\AssociationController::loginApp
default:
  path:  /{wildcard}
  controller: App\Controller\MainController::index
  requirements:
    wildcard: .*

homepage:
  path: /{_locale}/{wildcard}/
  controller: App\Controller\MainController::index
  requirements:
    _locale: en|ru
    wildcard: .*